# Generated by Django 4.2.7 on 2023-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_user',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
