# Generated by Django 4.2.7 on 2023-11-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_name',
            new_name='name',
        ),
    ]
